database:
  host: ""
  db: ""
  user: ""
  pass: ""

features:
  tab: true
  motd: true

motd: []
debug: false

messages:
  no_perm: " &4&lX &cYou are not allowed to do that."
  no_target: " &4&lX &cCould not find player '$tn'"
  command:
    heal:
      healed_self: "&dServer&8> &7You healed yourself"
      healed_target: "&dServer&8> &7You healed &r$td"
      healed_other: "&dServer&8> &7You were healed by &r$pd"
    feed:
      fed_self: "&dServer&8> &7You fed yourself"
      fed_target: "&dServer&8> &7You fed &r$td"
      fed_other: "&dServer&8> &7You were fed by &r$pd"