# Whether or not to send debug messages. Toggle with /ppapi debug.
debug: false
# What the server's name is. Will show up in /where.
server_name: "&dPotterPlus Remote"

# The db credentials to use
database:
  host: ""
  db: ""
  user: ""
  pass: ""

features:
  # Whether or not to listen for server list ping and set the MOTD
  motd: true
  # Whether or not to force the user to /getrp on join
  auto_rp: true
  # Whether or not to record the user's login to the database
  db_logins: true
  # Whether or not to open the character menu on sneak right click with player wand
  sneak_right_click_menu: true

# The server list ping MOTD
motd: []

# What spell to cast on shift right click with the default wand
shift_right_click_cast: "menu_character"
# The default wand
default_wand: "playerwand"